app_fqdn : "app.ghost.aminsaedi.bio"
app_ip : "170.64.216.119"
db_fqdn : "db.ghost.aminsaedi.bio"
db_ip : "170.64.216.136"
firewall_fqdn : "firewall.ghost.aminsaedi.bio"
firewall_ip : "143.198.65.193"
root_fqdn : "ghost.aminsaedi.bio"
