---

- name: "Install required packages for install NodeJS"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    "{{ REQUIRED_PACKGES_BEFORE_INSTALLING_NODEJS }}"

- name: "Create keyring dir"
  file:
    path: /etc/apt/keyrings
    state: directory

- name: "Add NodeJS apt signing key"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
    keyring: "/etc/apt/keyrings/nodesource.gpg"
      #state: present

- name: "Add NodeJS Deb repository"
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main"
    state: present

- name: "Install NodeJS"
  apt:
    name: nodejs
    state: present
    update_cache: yes

