---

- name: "Install required packages for install NodeJS"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    "{{ REQUIRED_PACKGES_BEFORE_INSTALLING_NODEJS }}"

- name: "Create keyring dir"
  file:
    path: /etc/apt/keyrings
    state: directory

- name: "Add NodeJS apt signing key"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
    keyring: "/etc/apt/keyrings/nodesource.gpg"
      #state: present

- name: "Add NodeJS Deb repository"
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main"
    state: present

- name: "Install NodeJS"
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: "Install Ghost Npm modules"
  community.general.npm:
    name: "ghost-cli"
    state: "latest"
    global: true


- name: "Create direcrory for files hosting"
  file:
    path: "/var/www/{{ SITE_NAME }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'

- name: "Rust Ghost install shell command"
  become: no
  shell: "ghost install --no-prompt --url http://localhost:2368 --db mysql --dbhost {{ db_fqdn }} --dbuser root --dbpass Pass123@ --dbname ghost_dev --no-setup-nginx --no-setup-ssl --dbname ghost"
  args:
    chdir: "/var/www/{{ SITE_NAME }}"
